In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import math
import scipy.io
import sklearn.datasets
from opt_utils_v1a import load_params_and_grads,initialize_parameters,forward_propagation,backward_propagation
from opt_utils_v1a import compute_cost,predict,predict_dec,plot_decision_boundary,load_dataset
from copy import deepcopy
from testCasesopt import *


plt.rcParams['figure.figsize']=(7.0,4.0) #set default size of plots
plt.rcParams['image.interpolation']='nearest'
plt.rcParams['image.cmap']='gray'

In [2]:
#update paameter
def update_parameters_with_gd(parameters,grads,learning_rate):
    
    L=len(parameters)//2
    for i in range(1,L+1):
        parameters['W'+str(i)]=parameters['W'+str(i)]-learning_rate*grads['dW'+str(i)]
        parameters['b'+str(i)]=parameters['b'+str(i)]-learning_rate*grads['db'+str(i)]
    return parameters

In [3]:
## check if code is working

parameters,grads,learning_rate=update_parameters_with_gd_test_case()
learning_rate=0.01
parameters=update_parameters_with_gd(parameters,grads,learning_rate)

print('W1=\n'+str(parameters['W1']))

print('b1=\n'+str(parameters['b1']))

print('W2=\n'+str(parameters['W2']))

print('b2=\n'+str(parameters['b2']))

W1=
[[ 1.63535156 -0.62320365 -0.53718766]
 [-1.07799357  0.85639907 -2.29470142]]
b1=
[[ 1.74604067]
 [-0.75184921]]
W2=
[[ 0.32171798 -0.25467393  1.46902454]
 [-2.05617317 -0.31554548 -0.3756023 ]
 [ 1.1404819  -1.09976462 -0.1612551 ]]
b2=
[[-0.88020257]
 [ 0.02561572]
 [ 0.57539477]]


In [4]:
#random mini_batch

def random_mini_batches(X,Y,mini_batch_size=64,seed=0):
    np.random.seed(seed)
    m=X.shape[1]
    mini_batches=[]
    
    #shuffle
    permutation=list(np.random.permutation(m))
    shuffled_X=X[:,permutation]
    shuffled_Y=Y[:,permutation].reshape((1,m))
    
    inc=mini_batch_size
    
    
    #partitions
    num_complete_minibatches=math.floor(m/mini_batch_size)
    for k in range(0,num_complete_minibatches):
        mini_batch_X=shuffled_X[:,k*mini_batch_size:(k+1)*mini_batch_size]
        mini_batch_Y=shuffled_Y[:,k*mini_batch_size:(k+1)*mini_batch_size]
        
        mini_batch=(mini_batch_X,mini_batch_Y)
        mini_batches.append(mini_batch)
        
    if m%mini_batch_size!=0:
        mini_batch_X=shuffled_X[:,int(m/mini_batch_size)*mini_batch_size:]
        mini_batch_Y=shuffled_Y[:,int(m/mini_batch_size)*mini_batch_size:]
        
        mini_batch=(mini_batch_X,mini_batch_Y)
        mini_batches.append(mini_batch)
        
    return mini_batches

In [6]:
t_X,t_Y,mini_batch_size=random_mini_batches_test_case()
mini_batches=random_mini_batches(t_X,t_Y,mini_batch_size)

print('shape of the 1st mini_batch_x:'+str(mini_batches[0][0].shape))
print('shape of the 2nd mini_batch_x:'+str(mini_batches[1][0].shape))
print('shape of the 3rd mini_batch_x:'+str(mini_batches[2][0].shape))
print('shape of the 1st mini_batch_y:'+str(mini_batches[0][1].shape))
print('shape of the 2nd mini_batch_y:'+str(mini_batches[1][1].shape))
print('shape of the 3rd mini_batch_y:'+str(mini_batches[2][1].shape))
print('mini_batch sanity check:'+str(mini_batches[0][0][0][0:3]))

shape of the 1st mini_batch_x:(12288, 64)
shape of the 2nd mini_batch_x:(12288, 64)
shape of the 3rd mini_batch_x:(12288, 20)
shape of the 1st mini_batch_y:(1, 64)
shape of the 2nd mini_batch_y:(1, 64)
shape of the 3rd mini_batch_y:(1, 20)
mini_batch sanity check:[ 0.90085595 -0.7612069   0.2344157 ]
