In [1]:
import numpy as np
np.random.seed(1)
x=np.random.randn(4,3,3,2)
x

array([[[[ 1.62434536, -0.61175641],
         [-0.52817175, -1.07296862],
         [ 0.86540763, -2.3015387 ]],

        [[ 1.74481176, -0.7612069 ],
         [ 0.3190391 , -0.24937038],
         [ 1.46210794, -2.06014071]],

        [[-0.3224172 , -0.38405435],
         [ 1.13376944, -1.09989127],
         [-0.17242821, -0.87785842]]],


       [[[ 0.04221375,  0.58281521],
         [-1.10061918,  1.14472371],
         [ 0.90159072,  0.50249434]],

        [[ 0.90085595, -0.68372786],
         [-0.12289023, -0.93576943],
         [-0.26788808,  0.53035547]],

        [[-0.69166075, -0.39675353],
         [-0.6871727 , -0.84520564],
         [-0.67124613, -0.0126646 ]]],


       [[[-1.11731035,  0.2344157 ],
         [ 1.65980218,  0.74204416],
         [-0.19183555, -0.88762896]],

        [[-0.74715829,  1.6924546 ],
         [ 0.05080775, -0.63699565],
         [ 0.19091548,  2.10025514]],

        [[ 0.12015895,  0.61720311],
         [ 0.30017032, -0.35224985],
         [-1.14251

In [2]:
x=np.ones((3,3))
y=np.pad(x,((3,3),(3,3)))
y

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [3]:
x=np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
y=np.pad(x,pad_width=1)
y

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])